import type { Metadata } from "next";
import NavBar from "@/components/NavBar.component";
import { Exo } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer.Component";
const exo = Exo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Power Up Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={exo.className}>
        
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
